### ISSUE TITLE
Feature - Restrict search results to specific country

### ISSUE THREAD

**Issue by HP8haNU7YxzBkTA** [b03tz/StoreLocator#3]
Another feature that may be useful is to be able to restrict search to a particular state/country. This could potentially resolve search quality issues where a search may reside in more than 1 state or country.

**Comment by b03tz** [comment]
Do you mean filtering on a store-specific field? For example, you would write the state for each store when creating them and the you would be able to tilter by radius and state?

**Comment by darkarchon** [comment]
No, his mean that the search result can be limited by the country or by state.
For example, if I search a Moscow(Russian), why do I need a results from other countries?

**Comment by b03tz** [comment]
I dont really see the use for this since we search by radius, I dont care if I have to travel over the border as long as its within the radius I specified.
